### PR TITLE
Enhancement/code style

### PR DESCRIPTION
**Pull request by SnowVolf**
Reformat code to match Intellij Style

### CODE REVIEW

**Comment by SnowVolf** [comment]
Rebased

**Comment by TrianguloY** [comment]
Quite a long PR, but that's what happens with code style changes.

Question: other than (I guess) using right-click > refactor, are there any other changes?

**Comment by SnowVolf** [comment]
Yes. Ctrl + Shift + I
Rearrange code + Reformat code.
This added missing spaces, indentations, removed obsolete smart casts

**Comment by SnowVolf** [comment]
Rebased again

**Comment by TrianguloY** [comment]
Reviewed and approved.
There is however an extra removed sdk check and an extra comment.
After merging I'll rewrite the history to fix these.

The only different between the merged pr and the rewritten history will be those two changes (added missing check and removed extra comment)

**Pull request merged**
