### PR TITLE
Feature: Update Gradle Plugin

### PR DESCRIPTION
**Pull request by SnowVolf**
AGP 8.0
Builds and runs successfully

### CODE REVIEW

**Comment by SnowVolf** [comment]
@TrianguloY pls create develop branch after merging

**Comment by TrianguloY** [comment]
Branch created, and pr edited. I think it's ready now. Just give me a few days to check a couple things and I'll merge it.

Thanks again!

**Comment by SnowVolf** [comment]
Any updates?

**Comment by TrianguloY** [comment]
Still haven't found time to review it. My apologies.
I'll do it this weekend.

**Comment by TrianguloY** [comment]
Validated. Merged!

**Pull request merged**
